### PR TITLE
Import template and defaults changes

### PR DESCRIPTION
**Pull request by leifmadsen**
Import template and defaults changes from https://github.com/infrawatch/osp-observability-ansible/pull/7

### CODE REVIEW

**Comment by elfiesmelfie** [comment]
@leifmadsen I'm updating the tests ATM to add in the tests from the old repo. Once that is in, this PR should start passing CI, (or at least give useful feedback).

https://github.com/infrawatch/collectd-config-ansible-role/tree/efoley/make_travis_work

I'll have to find a place for the template_generator.yml playbook too, and re-add the check for that.

**Comment by leifmadsen** [comment]
> @leifmadsen I'm updating the tests ATM to add in the tests from the old repo. Once that is in, this PR should start passing CI, (or at least give useful feedback).
> 
> https://github.com/infrawatch/collectd-config-ansible-role/tree/efoley/make_travis_work
> 
> I'll have to find a place for the template_generator.yml playbook too, and re-add the check for that.

Do we just want to merge this down then, with the expectation that your testing branch would just merge master back in to it, and then result in passing CI, and then you could propose that as a "Make CI work again" PR? :)

**Comment by leifmadsen** [comment]
The alternative is you create your PR for fixing CI against THIS branch, and then we merge the working CI into this, and then we merge this into master.

**Comment by elfiesmelfie** [comment]
> The alternative is you create your PR for fixing CI against THIS branch, and then we merge the working CI into this, and then we merge this into master.

That should work. Since I'm missing some required templates on the "get CI working" branch[1].

Once [1] is working, I'll do the PR against this branch.

[1] https://github.com/infrawatch/collectd-config-ansible-role/tree/efoley/make_travis_work


Edit: it ran suspiciously fast, but the o/p looks correct.

**Review by elfiesmelfie — APPROVED** [review]
Looks good to me

**Pull request merged**
